# Test Results:
# Fixed Tests
# Basic Test Cases
#  (3 of 3 Assertions)
# Completed in 0.08ms
# Random Tests
textbooks = ['Czsrc.?', '-a\\65\\M=Ij', '0Jl\\bzDGWB5', '7B?A@5SfKfi', 'zFA>ZKkC3', 'oTech/:d5ZONL2H', 'Q<meWz\\v0;', 'z@a_KR4SrxZhWp', '\\vE9/E|oce\\M1', 'uJSXUr?eXSp', 'mOQNgN32[g>^w', 'm:[|6l', 'kL6396', 'I5:FDrRLjN?5q', 'dz;7tY;z`8']
textbooks = ['rppq=ryw.Wa2Z', 'q>1im1twxgX', '{`F\\dQK2^', 'ueuVeI:;sD', 'juwrCkD9Y', 'aP]DK', 'wR.J6_<|@.RxwF', '^Epqe<{PQ=R', 'Kt.@vEW\\7y`', 'J4ndyB']
textbooks = ['.>rVC\\2>', '-BlfA>tv?d-GfJ', 'ku8v`f', ';TQDdFSd>', 't?@k1shG-nwwb', '5zxf5pwasH3EKr.', '>zGx<\\q^', 'c-e>@hs9zzQUG', 'laV>nrQs-Z8ZIiS', '|3XPqt', 'gR/m_6SNMw', '.KKZ=1', '/sHiOPa', '0G7x44JR', '4-\\_L\\TuPr{g`{t']
textbooks = ['@a|6Yz{`P;j', 'rt_k75D=uu;yka/', '.jJ5TA|A1b', 'NJvFM2>4]g', 'ru35w9-', ':[f3Zmr\\', 'o@C{Ct', '3Xe7.yS', '[PK]vJ.IfV']
textbooks = ['0d9Z@b._>Z||', 'sE/O3=|Qe|1v5H', 'Y9uJ=119.', 'dOk;;S-2', '8-0<5JAgJ:Qj', 'wX1T3kk-a1']
textbooks = ['mP_t00uhhqNkh', '=zuOyA.8>', '<rKN|:t1gi-]k', '^OI;A<QHwQHOjXk', '=r.0Q[j', 'Y-0[_vJITe\\U6>', 'jl|myO1-', '77qROJHr7Vz4', 'zJ_FDJBI23xQ']
textbooks = ['wfD5YWjq?724', '{m8LrCD', 'Y`/571j^PNENT', 'CdF1Q^', 'tJjB28b6t', 'u<:kQwi', 'T^xcXV', 'TyHypyaLMS', 'E=igBep', 'U2L-EqO9h1ZKI.Z', 'b.?K\\|Ib1v', 'IdmdhnK1:[NH[?[', 'GqZZT']
textbooks = ['nmq/?[:4', '=_7MW/Nlu', 'N;Ma@TQg7hpF9bm', 'XM.mE`bq?^Yv;uj', 'b6pDNZFKyino^g', '2Qk-q5zWDd-R', ':/PS:=A6SmAOF', 'Rd{<owE', 'OT-KrygUm', 'Lr5bcGK', 'A_Bjpv6^3Zqs', 'MHO_TF{RH\\^/', 'fPQhkB7pGZHhDuc']
textbooks = ['ArLTtmr`', 'dGiYyF^Zg', 'OlJW|LO-5qBj<n', 'e[=Db`ApmA.^[gD', 'yCZlZWm192>g2Ec', '`XlotsH_g', '\\RoHZZuI', '8@PuV', 'KqM7[9>eCR@S', 'O6]N8W', 'rJ7Yw|ht', '9aYJyVVF', 'EE=udAK\\', '[|[H]D']
textbooks = [':<>fqr|T9uROq', 'rh<ZVLsEP7O/zH', '|Qtw_hh2Hn-4r', '1|fW05Iw-NE_c@', 'Vv{073', 'E|kta7', 'pNud|', 'IV{xt:W_^^v.G1T']
textbooks = ['d6PS<j|[', 'Iq>GQr', 'E8rEi;Mj', '9TVHI:Uly;', '@\\8AK7e_Og4', '>J9WqA`QDc2', 'Kn0hNIA4t', '=clhtw.', 'Orat\\', 'HbJV7fUWsD>GMu', 'rMjGwAL{VF-Cv', 'bBJ^ap<;SHnlQtM', 'rBb[QA1w/tg', '5sr1>']
textbooks = ['Sg:G/pMxzNI', 'j1]34<wbnd', '>m^3h07leQ', 'fO\\OS5Hp', '-AmKo=', 'w?u>|', 'St=<@I', 'h:0jg/\\9a<l', '[dH?yB?W;Q', ']t?@KX\\@I', 'dv19Qf[V0k0X', '=`AGMr', 'Xi\\{DfEHu7@XC', '`RaNAN8^{KF1ed', ':GWNX']
textbooks = ['Y3vJEGrsu>D?md', '82d=_', 'Xj;Do|cf', 'horBbV]H6', '/IR@ssdv', 'f/?bo', 'I\\=.3G@7r1Lo']
textbooks = ['SCM7^HqH0]', 'qZu/_Dy5IWB|', 'GB_Ly', 'U[iygU', 'wZ7<ZFGST', 'Z[<CQpLq;', ':6xv3J:>-Xe<3', '/q]?z9wg', 'S9;rX?Kq', '0qlprS', 'Vd=QybXWhZr_\\76', 'oprncNV{M3', 'V`]I|kY', 'GHagxXXY:5Opvsk']
textbooks = ['rIQ>HV5', 'B4;l`3R7klA2', 'Pc\\hICe', 'bd456Vje6ay>', 'xWR-CXjL9h', 'LkidkMeU2U', 'KHxXVm6u-fQ;1U', '_:Nvw28xYvJx', ':3MtAo=I', 'uDw/nTN]rlq', 'hT]B>l<aIn\\']
textbooks = ['>[TKtaio;.', '1@QA/B7@`', 'e8Zn8<6Q3', 'OnY9y|xf6AS', '|{4f`HXq>Zj2E?@', 'gI1h1Q7', '=-KE/uzU5', 'B=tv2cHehv', 'r30oK3lf2_', '?S-mGFKt', 'w9^[h>^uvlc3Vd', ';]0{Kw']
textbooks = ['O8|o31n[H', 's9x6QyR.ZfdMbx6', '/Qi=Amr:Xw', '<LAxF-', 'Uagp98', '=T>0[mOY/=t/cVj', 'V{v_6k{_', '-faNx5nQImFz8', 'gRc7v', 'Rm[yqnC__\\hM-A', 'zH\\JSb.', 'PXrnB[V', '0tCYwqLWK;H]:', 'F-U<7{x|]o|']
textbooks = ['yM9K_4u|j7', '\\YM?9NJ2Q|^]<o', 'GU@9DvNdJ{', 'n5h>@j', '7HO3x4ae7.9?OT7', 'LqxC`', 'D`eemfHkc', '2mRJhRt>f`RO', '\\0QDHy{;R-k`', '1>OZagk<h=AiZ']
textbooks = ['a/[G{\\n3FcE', 'x2BfEsVU/pRc6', 'rp:suRsMI', 'Ln[^lEsF', 'j2|a4', 'r4A.9J]fIb', 'AC\\zGvCl\\ZVSKTN', '\\AgmsSt2Y', ';6fn17JT`o', '`TI17Xf@XJ<HVd', '-`gIQ', '/fCxFZc=', 'FmyMgUFT|Xt9AmB', '.xNDew^374', 'BOQJiCKO7w']
textbooks = ['dCTX^Jwv[2W', 'B`J`Mc7', '6Gu\\/0;brS', '??:ga6t\\lh<=1v3', 'UI<Q.D[.kmayY5', 'aL\\TK6otu;|', '3aX9RYXBPz1{ya3', 'CmNE7X7\\SgruJ', 'ho=j]N', 'nX5\\Nrku>t', 'uo>Dl', 'Q-.ViBlM=m|KqP']
textbooks = ['3L<oj71o644E', '\\L8@62[O[H', '9L8_T<', 'v`kH\\y83', 'Zk`J:HxO\\d-', 'hh/ZUjKh?G]', 'W[l^mHnfR\\cS;', 'MDCyHy/0->c', 'kwz>vXH\\;4Nciy`']
textbooks = [':/o9p', '|R8z7.fp{e', 'O6UrE', 'JlC6P[/', 'Zn9OzBTq{', '0-o2BPe/Cz']
textbooks = ['p3LgcCf5ZX`3hIf', '=NWf/', '^>HOmz>qna', ']t=]bM8;VP?dCm', 'J\\MTU9O[', 'cT=J5yUyu']
textbooks = ['m_Z3;8q>F`>I^LK', 'R04;ya', ']sLnZnVWl', '>04Y;K', '0-.;ACue7eCt4`J', '4]@n<ooe', 'k8aKdE>i', 'T]_LgDI', '-TrVWuF:vtu4nj', 'AMJhk^8j']
textbooks = ['xb06yoAdpTGd', '8l|O.e0K', 'j6o_]x;y', 'jrSso9ix]P`2Mg7', 'Of:i4^o']
textbooks = ['p>3Loo', '|u7l`/', 'vv;tVUf?-Be', 'cl\\j@pe?2|3', 'sdQIe', 'uBH8ng_.', 'V7S0xYc-V6=Ps', '|u3`uRMhn>7/c{T', 'v-2ddhYJW', 'L.N2Jx<Ul', '<ju\\cW2atH]=b3']
textbooks = ['MKu]Mfk', 'D_eE[Wfh8v', 'bcdfs', 'oxOyVUL', '60<3cubBe', 'XoMO=lq-Q/', 'GM:ts', 'Y?`<QOj', 'j43cvFFsI^Pzz', '@:0Oxz7@:Z']
textbooks = ['i8535^-kv3m', 'gjdSa\\c', 'q70|CvWXZG7\\<', '4H|Q_{K15c./o8W', 'IplUEYg:uwIJ3d{', '[HG5Avadz-8K3', '@5t^sCk=f6ui=V', 'WlEjP8/1sPB5', 'Lciqb{t]>q']
textbooks = ['VVK_H`m9{L', '|yqbI{?', 'ZuC1;{xealFd', 'zJ@JuoBXOL5|x', 'cv?EsFl:2QR:<R]', 'KZV`7@hX6b']
textbooks = ['.6Rew', '<w77AKhI?PEpn', 'uDecc-H=vE[Os', 'iGB7^ji', ']JDJj', 'r3V90', '8YVIS;ZO', '`a3^Pb1z8G', ';fv^I\\<7=Wn4Pg', 'DbchRfKx^[', 'iG4-VSGRv{t<8']
textbooks = ['-JLst[6OXlfF', '3k|\\4I|n:-89f]:', '[|^pnXtK;7T/5u3', 'P]Fx;:Q8H', 'N`L]P', '=kdNiaw|KMgR', '[w4]u0bdW.tz', 'a2d=Sp|1', 'K=/06:K|2CD', 'TbpnHycM', 'dDOe-e^;j:', 'WlkRw', '9.lp5n@H[L.D3g', 'RLRk.Lco9Q', '>verk>8=AYMk']
textbooks = ['II<TzR', 'zthrrVgmN', 'K:^WY', 'w41.SV>:<@_cKbq', 'tuuMeb\\m', '\\_MbICE9UC', 'CEX5s3gfX.']
textbooks = [']6bmiml\\Q1a^gH', '=z]tg8:Z6/', '{^DeCg/4.Z?', 'Y>8.V[-B_?gEB', '{J.t>tZ[/3;', 'j`>eRWqx=yU0j{', 'W0av1\\w>hXZRC5', 'YmSP/H', 'y`xN_Jd]K:j', ':Urhi']
textbooks = ['l8u:^WZ?1', '6or|D;|U>', 'Gp`{a', '9KG_.OX2@H4VR2', 'OY^JxThOcy{1', 'XnaOB:va>[{x<Z', '5^lk1-;E1wZ', 'eDQ|jE-dGrBAnk', '=ZQzaXPd93r:5m]', '^;mfbBmy@', 'slOdWrzK', 'Pr7O2O3F-zdKy', '|k0yG`CyW?Q-Eil']
textbooks = ['fPnhH:', 'TD@0]7zIdh[83MI', ';nX{>>Rh^Jxz`', 'MUggdIgw', '<8XFSbDu{KEX', 'lXc|wav=X_', '>Z^davM', 'Y_Vpu_Vg]A6', '/HKpYn2W;gwU', 'wP9j9W]h0w[-', '0cHfuKl', 'Nbl[VP<gu', 'wUewlvr', 'zX:7KCjvK[', 'z-UT_9xpAPd]']
textbooks = ['Ue\\?/8Umx', '{6e@mx2g<', 'jgyW-s2c', 'qB0syB', 'rJ=s-Ii2', 'o1JjTcKNKn', '_uV=sH2bP_f0.-', 'SQ?infy_A', 'Ihst1>Y', 'T=n4R_G`NV', '=F>>D5>']
textbooks = ['9Z<z0I', 'mkMM8\\dRw`', 'JWH<k-nckf', 'Jm`rM>]cc==4P', ';D7f_VM', '/^BgMy01ykWYd', '?Pt-5>u', 'GLHe@WSTlh\\v[oF', 'TpVk/.CE', 'dse9i', 'qKQPxQY^:fN']
textbooks = ['uxu2JJ`3I-u', '_z=xi', '\\LA84;FfG^|{J', 'jW`b;Unv=8l', 'j:f2|b^;i', 'JB-`RrL', 'Khs[u/1sIR4?^', '^x=A<{CfyZ?', 'BeAY6TpIS', '5litj', 'H@cV/U8HOQ', '\\huU5?t-uHh']
textbooks = ['g75aCBes5pT', 'KA|{z-CucpCID', '[HcuxFfO/', 'pmu\\4M', 'K][D]_Q|F', 'aZi9E', 'o-dVDW]', 'ye9i@`', 'RcGds|XyVhZZNdo']
textbooks = ['zD_Ud3{nw_6', 'x2{/3]VJD', 'lPz7wE]btuCJFbn', 'ylDZueJ', 'jB=r\\AkWJ5{[m', 'D45zP88WwHX[Qv', 'Frm?xD6G_', ':NCC`S|PIk', '8IR9<5[@LX', '<eyCtWe@', '-aRVLkGPMhE;U:', '/oIO2']
textbooks = ['riAgP6[C>', '=Va|TIVkY', 'o=JnkKXrJn', 'Vj3lT5--b7', 'IIJc-tv', '3go|>Pkx=RvY', '=0=CD^z?s6@', 'xRSiNXHr1f|Q.', 'MZCek', 'TGiPtN;P', '?xlcP', 'HJ0_A[02', 'tl[DEbmmI/TW', 'IA0R{lqT']
textbooks = ['H1sZmK]', '1cxbmRt=0', 'at]cPOzu', 'sIjp_h-', 'j>/sJu{1|jr`', '7Np{0Ew', 'fl;r[', 'b7chJpZ.O\\<TV', 'l5|^|', 'YUPa5SqV2rr/n', 'VGSn7Y', 'TFK^OOj.v|zSpN']
textbooks = ['\\[F|rjxx<', '\\4>6_Dpr', 'yU6^/T[;O3-N>', 'j=YkNb8uUtmhx', 'Hbieasceo3a`R']
textbooks = ['8LfLt75\\B:82@X6', 'Vk>;zyxkr`/K', ']tSa:', 'UJr9qz3', '4CDrEX[BE@bl.V', 'CZ?w-j', 'rTx^iT', 'EFMR8:y', 'vQ`{HW<[r', 'qu[4Z', 'oye`k=7/', 'bdwG:_wG^|7vfSZ', '`jT^gH0']
textbooks = ['0a7rSRUzv^XED@.', '6L0-@<z=5o', '.]@@-tT2iQ8gB<9', 'Zz:?Ne', 'ftH-d^7\\{5El8Oi', 'Xn6^n', 'fud_1', 'g97biYulxT^1aB', 'yO5[|uAO_9|51', '|.nZ^Tga<[1U`', 'dlXz^Tj_{uZLH2>', 'Nq>-7LE/J_g', 'f3Xn/G']
textbooks = ['8DlEmdzc4cq', 'LYeNNgVb.', '`X?7P>4F-]A', '<v\\t9[?q|wCu{m', '@q9ni/JjSFQMAL1', '04L\\xDqYzNRRdI6', 'dstupH:j^f_', 'IlSmRIWT=dVC', '@RI<2ehdJM;x']
textbooks = ['@z=D1lmH/', 'rrx6:Zj9NKV', '=XgR;BYIk<', '<ovn2v\\vHt:jEcl', 'HtLL:', 'xtW`T2joqeZR9', 'En-37h]0.Va{X', 'khO-\\rfndw|t', 'voww61Tv8>', 'X9z]:XFao_', 'RfL9gTO05[{', 'GL^@p6pfu>7>Y']
textbooks = ['QnbvI>nm<', '1kWOZ', 'F<P_J-L>pm[G7', '3?sd\\[dFiJmU4', '1K0wMn6A0jet@`]', 'KeWzfD?4V90aTp9', 'YWQP|', 'E7cD\\{']
textbooks = ['c?/N|7jI:NJISd?', 'Y8y6\\Fj2=o|wW', ']of95`z4N', '\\IxOr0cm', 'eD2BJ', 'xjC]NY3u', '^gFpE', '7cG=ELX^YsQ', 'JwIPDc', 'LdYF@1MA^9']
textbooks = ['IjoDD', 'v4a0dz_Y', 'Cymb3/R|U', 'z[\\i@@igxzD<', '-EV[PJ_7t@iuaSj', 'Xh_eyQ{', '=?x@rX', 'j.{q6x`/>hZ', 'VsC0P<XxZ0qJ']
textbooks = ['Y\\|-AuFdb@T', 'x|at;MoG0ISf', 'ygcMN', 'sbI-ETTzKVjQ2@A', 'XqacAXLhyR', '/RwuLoDYQ{Qlor=', 'cqU.VtABDS']
textbooks = ['|ymB.TScWv2', 'kzVlY', '^p9xnH0BabWYS2X', 'V1Ch0gJ:`', 'Cl|[fipLE8F6-', '1H`cKIRNl-dHra', 'K{e21G[jag3', 'D<_@ye1QWdL-rj4', '0f/<MuA{Fi7[', 'rl5Zdr', 'Nzu4k', 'xjh>P1V5C:y']
textbooks = [';J<7Vhrm.r', '6sO/48s.2', '51Tg2>pNbCfX>Uz', 'G[K<YKTHaf]BZ_', 'L=07_', 's4yXp7K5`U', '|MhKXE@FkyU2', 'sffMw=W7L@[U']
textbooks = ['u\\D]S@OTV0<', 'uIJ4vJcM`S^hkG', '44S1A', '7iYcA_6^', '>e[67', ':[y5qTJ', 'ul-pb:?m', 'OD;f^77;<`YA']
textbooks = ['-[H4c2F8Y7Y', 'Sa533BT{ob4{', 'YIuIdIb_', 'Pg8kbrqmD5E84.', 'EJUpSzv[TWJ', 'cZw@iE2hOz6\\7']
textbooks = ['N{2-:rn', 'b;2ZH5OPn', 'Lee/-4Fh8mT', 'O?p2;qE8P', 'NNEE@']
textbooks = ['G;k<d', '{j-hLeiDdUwAS', 'Wqbeb', '9w]Ff:^O', 'xb1eya/4', 'vTNaip|Cx@:', '-Tz.m;HW3JXQ', '.lGK3_Z`8D', 'ZT@M{LPAsj', 'Xd<Xqi3I', 'zfQo2vAn@J300m', '-KTyfjP{ab', 'QS<HM-X']
textbooks = ['?vPI<=', 'gp{K[Z\\U2Ot', '-qA75jdsEjew', 'DC5QMi', 'I7nzdxMXrfI>qL[', 'yZTWgr^?9`@iq', '?W<R9`X', '{L^v4S=r_J', '4[=NS`eN88Bv2@.', '3O>ybsq3`8.Fo1', 'a8igps', 'WXHDWg5UTz7', 'RvSEx5]4\\|BsSTa', 'H{roa2]P_L^jf{\\']
textbooks = ['yar|9;I^8', ':R^hD6p', 'sYbHHWoikpt0=', 'J1PE\\iDl]c', 'g<lE_', 'W2YAh50OpH', 'nGquLv8g|', 'cYSys', 'JKTwZHit']
textbooks = [':woiLFqt2@>b', 'mLoiBuhIDw\\cDq', 'bqVm^ml4wZD>|0-', '2L2?CXCyA|gjS6', 'lr0aj', 'Quz/Zo0QMAM;D', '8.`S]:E78k_J2', 'o5c2n', 'F>@/LMaxmvD:', 'XAcbZ', 'C|RJfR{6/[rNG', 'EA/`xIXQ2u', '6Y-G^V_', ':BL=711\\/`fW7.']
textbooks = ['M]tS9qe_jh', 'IY@i6.9Pk', '[{P>9JkDgOCsl', '2xmU<', 'UC2;-]V|Y', '_yhu761', 'hbnLvFh-', '8O\\tsg`5', 'llpT;p{', 'XSsABdt\\7n/', 'W-a:d-0K4E=SZ', 'UA6xP/aEr', '^HG^Wfyb', 'EqdYK2y']
textbooks = ['4xT4Y', 'SvmN9', '[6-T]0mmJQnTiW', 'cqIRt^rlQMx', '_^hs|[NQ>]tHMI', 'j/yhJ', 'j4IC1ogM^a6|^-c', 'X{JJs^]K?.zZ]']
textbooks = ['rbbXYzK;37@`tJ6', 'xqvxNyhC7J', 'W6;VADBKIH/dj^=', 'jd<rj', 'xQ9slN3<<uL9u{F', '[i@.<Klw6@\\b', '?dx7fXMZdlh>lHQ', '/Ver<l`pb', 'NG2Qpm0;C', '.-2H0yD2>Dm7O']
textbooks = ['RYytR8M', 'syIvs9H', '<mUU{{q:B', '{[ij=WaS6F', '6Gj6oBb|h@0_', '0:5:OZ', 'NcXhG', 'R03/vBagbFa/X.d', '^]38.h?fY{ln', 'x8A.\\bjx46{', 'H1K8\\VfLb', 'G[fYc5a94YYrl', '6aCIqep3m1:fpW']
textbooks = ['St[/Z<', '@g9k7=', '?b2p>Gey_^s{', '8U7QJiC\\', 'I>Ma1P']
textbooks = ['n\\_N\\/6N2R:tUKr', 'I;kuyAjm;p@', 'e457LM', '^Qbj_Gb]Hv4F', 'TMY8QBKS6|IIwu1', 'BK=WN|IDwM', 'SGB@Ov9M{[<R', 'p]ZyhgjtN;', 'R0;OK3DI', '0PjULw_X5a', 'pppf[u=', 'GIR9YLRs0', '0H;DsQ^M_Nu', '[j1Y5nSG/]tl-']
textbooks = ['c]8L:o_', 'GokADFQKC[_]D', '{jdK>B@v_>8><', 'M-[/_xG@', 'F^hk]5j8:{;Pi?', '/^DxQbD80Qj3', 'U>:;TrN/mS3m', 'slt?=', 'DfVZ:', '<-sbLfrLb>h[o', '|S[]k', '-r\\aL@@']
textbooks = [';^_kP<A', 'eq^s\\gC;b?Us', '3w?Bn[-l0UdkDx', '>R1A6f4i', '\\ZAXgH0', 'DGyEZ4Z8zLT{\\', 'Iocb^t', 'VaTu7Dte;', 'VawqUFTRJCO:B/', 'y`1n4jn;', '\\JF5eYZ^W8']
textbooks = ['[em_Dlsi`{d', 'h^:1jL', 'sV5:sQfLDt0Zwb', '-g?Q|hJXXX;UAQ', 'Ot.wAs[<YCM2']
textbooks = ['-v3r@{L-TqX', 'I{MnlKt=P', 'Xln6x[UjsQfr@', 'brLoDpE7', 'N31t8sYbP', 'YSaaGn0j', 'nz5`c<]y{|B.e_', 'iMI/6XgJ', 'fPZ<o[v', 'h7^8MGWLFR', 'kyHAUlrpQ']
textbooks = ['3Jd|`[', '?1V|pT', ':kwTm\\e', 'bY-Y/', '`Itkk9|5u', ']-nVHKnzsT', '|AbwG-uTEUJFHk']
textbooks = ['8M`rI', 'l^.t{', 'QQX=K@k8:xu`', 'NpW@bbIT', 'W<_/?A{', 'h1dYD2g', 'Z@9o3/', 'A9^g;[', 'gaWX-d-n50', 'wB=<r:ZtI06e{', '-bF|R4Bj6a', 'C]LAE{wpTo]Eeb7', 'XVjv8lNq', '5\\{42XD=qg']
textbooks = ['6xG:e:<H', 'UKl=;Qjq/', 'T;qJzGDDL_1hXx', 'Z=joxB', '`Cv|jLdMNA9T5?', '@;O\\FN]0DBX', '<:GOEZ[VL-1>m']
textbooks = ['=g]-.Y4', 'qqA2:sYQ=|o{zc', 'KzCgX/FBRknx', ':cHgx=fi{dff', 'VHe@G6JoZ{', '>VkR:mn0']
textbooks = ['8NZ3f', 's2k51xrApi', '.\\K;W', 'JEsL<', '|d\\>EClCq^']
textbooks = ['AaeI?s2Y/', '9t{`iWvd', 'QD>1X5K', 'j20tK<biage', 'Lal{^', ']-fvEG2daFzg_']
textbooks = ['xHyx^', ']G<:|_;S;JR|.', 'BZ4Fe<9', 'm0vz/Z:f;', '{1T=lw>ob', '?7]2EoVd;H{;6Rs', 'X[jI3u', 'y{aH@gu', '{0w-vHfq', 'GKiNZKU0_Yf', 'VoHmeFlv', '3NT^Uyshu', '4;{Xi']
textbooks = ['<PA4=93HTEpf4s_', 'P8o\\DWFrMB=', '2eI`QgU1YHv{E', 'xRr/|@', '?Pb8|pfdtjdb9jT', 'lF=]Zy^J2COs.y@', 'P2c;gGg4xCbN', 'T:||nySHL:[1lj7', 'Zp9]1X', 'K@VzD3pCZ]`]G', 'V\\wL?mvW<9T']
textbooks = ['AAZz3', 'zHzfih{@m@ajK{', 'xoZM<', 'n1b-z@', 'G7mZ`2jP7Umz', '?-HL=xPlPYNO', 'l>u:2|rRqP/']
textbooks = ['FACgY7BNZAO>[', '?/C;8Kc', '\\l9xGz|a8zNz.', '\\Qz=T7.72p=qyn', 'IKSHN', 'e=pboO', 'Ta|\\4U<n', '5K[QY2zH`k', '8oCu_L', '2aM5g3/|', ';RgeQEzgCJf.Lg', 'kz@95Dt', '>=l/u=`', 'oyTL[:vI:738/w']
textbooks = ['JB.TKdUN', 'rd=betxZ', '8xg;8', 'X|Rvs`gEh[7>a', 'hjlvM']
textbooks = ['5`Z?HhbBA.nNk', '`c4cgkbV=]C', '\\Jt-pWestGr', 'iCLnlCU/uhq<u=', 'XuDEi:ih|<0', '6Jb?C<aGt]nQ', '-z2f^{bd1hacAe', '/<FuCd|h1cX<', '_1cMjF2M', '5S.9RChnNR{.s5H', '<_/E0wA4Ji?', 'ElH[JenP']
textbooks = ['u9CR0M4tdMn6r', 'D<Lsy', '[7V3P', 'Tw?tm0', 'eMwNgWKLuH`0hs', '3=D?3fa<Buu-HS', '3eYd--y{', 'EGyhuFgWJbj^', 'EJo|8u', 'mi0sBtLp]MYR', 'Hy<9eDezk']
textbooks = ['3^/Fa', '\\i|tA', 'SJlzLz.bVFcBE', 'aAkDcx9', 'p9[bMel{']
textbooks = ['1iHJ1>1y', 'jUu.Z4<_HCll', 'rjrHQ=I', 'Qp>S6zkRA>n]G', 'Qm^1Vf;R;', '1oT3XU^', 'Eib8@', 'oLE0vtezrEK', '/q/t<a', 'kCEhpKx-M/oc', '9d7o?', '-\\m{`6{VW', 'J?3fwmhZ']
textbooks = [':J=?e^^\\m.wSCA\\', '{2H^0=cc/E[L', 'o^>I:', '[yefIWUvyO', 'VvMMQa|][e]A', 'o=i{;FmO', 'e:/Y5-k', 'rGIUjY9[oaQ.4', 'sNujI0zuhc<EXL', 'PQP@sD^w', 'lPh1jW1t', '9_V7>JT7ikW_', '|dwPDS.-fx', 'WO6V1\\lc', 'Q{N^.Q2|LR]ZL']
textbooks = ['iG8FGKRX', '_ZFfuHclF', '6TD_1_/gK7pd', 't`j]t?b7B`35', 'S;/C{W[U>[M\\n', 'w]=zoqG@Mue7', 'x5;hB^lVA|NpL6\\', '=m]97dB/6Y', '<TXaHlR.OOAUK', '9HW/2z^_D0_Vs\\', 'C|pAZ/`RAU', 'U.8Uh=pEpXS|0/', 'b41?<', 'K@lDC[PYo']
textbooks = ['Yrog0`=pRr2n<Pz', 'Ek8;L;TsGf', 'V=._qKuNp', ']c?>=Ha0Hz', 'FQAS4fry', 'K{/ghXgk', '/sgzzu', 'aYaBxSu', 'DoA=h?4WHWsPy', '1_ofI@G']
textbooks = ['NtkcES{KnL?', '5@l.|TRDe', 'D;bgHV`D[o.Yml?', 'e0Y2c', 'fgdnxAfe?r', 'grinl8DU_q:0', '_kyo;Um', 'i`7@4C', '8<^58', 'SUd|r', 'SK]`qHdFnWt', 'nmsxZ{Kv@]^w', 'A5DI^4o']
textbooks = ['Z=NgkuK6', '@WpWz:B', 'K;y-l/E.hC', 'QJn=cZoTq=', '-T[>b', 'Ncc2|:bSnX4', 'p4nq5Ml\\:<f']
textbooks = ['4=jeu9thUX;s', ':DRfs9b;cUi', '1L{AcAai]5', 'qV6FV:QZBHtjYJf', 'H-sxTwF[', 'Eg0KE7wX\\q', 'ouW>s', 'hxyxY', 'V-T;o3J\\{cXwA-', '_r\\^@_:uJ>', '^yryJl2J;b', '/]k=kRFj7-l.']
textbooks = ['<PxbY=Ub8Gf3:', 'EE4VXcl5H?V', 'K>E|{?ejLOq9', 'hhT4x\\hHwii', 'Ekg>Y_`og_xv0.5', 'G3LQURzhM2_o3', 'n|7jZib=_]=t<M']
textbooks = ['5\\qO{', '{{bjeVXkzs`i', 'j2I2KZgXOp95', 'B1onfttB^`RsoqD', 'ZqdB^V^^A<2', 'iV7Lv88S', '<f?.e`>F0Mz', 'Z:9KR', 'Wp.AM\\Lv', 'Dpa;ZD', 'd_EQJ', 'pSqOOO]@-<>Y', 'G7L4CyJ']
textbooks = ['<<3wt`{PACC', 'y[0s.5l=VV6UKVs', '0:Qy@y', '5JUpy{9jXnh-', '[>5QVZ24', '3hFq3sBPjz]{J', '.7WD:f:', 'O0y]SL@4@', '|J\\XlIrT2;ai922', 'J<C-y.A', ';dTSL[:T', 'SZTLFT;`48q', 'J<alp\\|C{`TMyAj']
textbooks = ['75]YLg:wr', 'Q<w5\\.0UQz_ENzS', 'oFjdW.vdD6=-', 't=V=q:vKJG', '1f@aeA_?-', 'f.`<.gL{nAz', 'g=|<W-j5', 'e^1m?rga\\<1N:<o', '7Q|_`>gH-', '.[h\\7^jtNR']
textbooks = ['Ynniv;Ys6<?@ZT', 'hh_ZAHq', 'YUmz:|6FdEQByMp', 'WitUlP87', 'MjsTgkguYqx_', '2fAGVPX-z', 'qXKTxFb[Px;1aj', 'pZXg<:ezdm|', 'f2NU>']
textbooks = ['.p=EFx[', 'Jdu5?PSJqHD=y@', 'Ibc>Ev1l^U', 'czM4UrY4p', 'Bqwe\\ghG1tM:Ed', 'HT<M5[FR>xXlS{h', '7qLpy<']
textbooks = ['sjFNV{Wbt?;1r', 'TwIJpc4', 'ruA1h{5x2Hs|', 'j<69T<F<3b9', 'eSOsPQ/Q6d??X', 'YG^d@', 'cnwgnmE', '3BK9VmO@zmx.\\ZJ']
textbooks = ['SCFb_^6dI0=AP2', '0[@:dvA', 'IzldNnt9VK2sa', '6V`C8Nn', 'N=0ij9`', 'j]-Jx', '[n3c[oLjuEI8]C', 'TZ]kPJo6O', 'mjys2H>4q.B']
textbooks = ['zzbh|N', 'o>F/>U.OF:vCZ1`', 'tB7eN9lF', 'Q-BL@VgF?e', '.=zW\\rlW/=uewQ', 'v8yN/<JSQvJc', 'LA\\dIX'],
def sorter(textbooks):
    textbooks.sort(key=lambda x: x.lower())
    return textbooks
sorter(textbooks)